CREATE OR REPLACE Procedure CALCULO_PROYECCIONES_DEAL 
AS  

    DROP TABLE IF EXISTS TMP_DT_DEALS_PROYECCIONES
    CREATE TABLE TMP_DT_DEALS_PROYECCIONES(COD_DEAL VARCHAR(21), FEC_NOTIFICACION DATE, DEAL_ID NUMERIC(5,0) IDENTITY)
    INSERT INTO TMP_DT_DEALS_PROYECCIONES(COD_DEAL, FEC_NOTIFICACION)(SELECT COD_DEAL, FEC_NOTIFICACION FROM DWH_DT_BASE_PROYECCIONES
    ORDER BY COD_DEAL)
    
    DECLARE @i INTEGER = 1, @deal VARCHAR(16), @fecha DATE 
	
	DELETE FROM DWH_DT_PROYECCION_PAGO_SOFR
    
    WHILE @i <= (SELECT COUNT(*) FROM DWH_DT_BASE_PROYECCIONES)
        BEGIN
            SET @deal = (SELECT COD_DEAL FROM TMP_DT_DEALS_PROYECCIONES WHERE DEAL_ID = @i)
            SET @fecha = (SELECT FEC_NOTIFICACION FROM TMP_DT_DEALS_PROYECCIONES WHERE DEAL_ID = @i)
            EXEC interest_looking_forward @fecha, @deal
            SET @i = @i + 1 
        END 